@startuml architecture

object Backend {
    エンドポイントURL
}
object LocalStorage {
    ローカルストレージ
}

object Components {
    UIの部品
}
object Context {
    コンテキスト
}
object Hooks {
    フック
}
object Routes {
    ルーティング
}
object Services {
    サービス
}

Routes --> Components
Routes --> Context

Components --> Context
Components --> Hooks
Components --> Services

Hooks --> Context

Context --> Services

Services --> Backend
Services --> LocalStorage

@enduml


@startuml hook_and_context

namespace Root {
    object index
}

namespace Contexts {
    object SampleProvider
    object SampleContext
}

namespace Components {
    object SampleComponent {
        object useSample
        object useContext
        object HTML 
    }
    object SampleComponent2 {
        object useSample2
        object useContext
        object HTML
    }
    object SampleComponent3 {
        object useSample3
        object useContext
        object HTML
    }
}

namespace Hooks {
    object useSample
    object useSample2
    object useSample3
}

index -down-> SampleComponent
index -down-> SampleComponent2
index -down-> SampleComponent3
index -up-> SampleProvider

SampleProvider -up-> SampleContext

SampleComponent -down-> useSample
SampleComponent2 -down-> useSample2
SampleComponent3 -down-> useSample3

SampleComponent -up-> SampleContext
SampleComponent2 -up-> SampleContext
SampleComponent3 -up-> SampleContext

@enduml

